//*****************************************************************************
// Copyright (c) 2014 Texas Instruments Incorporated.  All rights reserved.
// Software License Agreement
// 
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions
//   are met:
// 
//   Redistributions of source code must retain the above copyright
//   notice, this list of conditions and the following disclaimer.
// 
//   Redistributions in binary form must reproduce the above copyright
//   notice, this list of conditions and the following disclaimer in the
//   documentation and/or other materials provided with the  
//   distribution.
// 
//   Neither the name of Texas Instruments Incorporated nor the names of
//   its contributors may be used to endorse or promote products derived
//   from this software without specific prior written permission.
// 
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// This file was automatically generated by the Tiva C Series PinMux Utility
// Version: 1.0.4
//
//*****************************************************************************

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>//added
#include "lab8a.h"
#include "inc/hw_types.h"
#include "inc/hw_memmap.h"
#include "inc/hw_gpio.h"
#include "driverlib/sysctl.h"
#include "driverlib/pin_map.h"
#include "driverlib/rom_map.h"
#include "driverlib/gpio.h"
#include "driverlib/interrupt.h"//vvv added by user vvv
#include "inc/tm4c123gh6pm.h"
#include "driverlib/uart.h"
//*****************************************************************************
volatile unsigned int count = 0;
 
void
PortFunctionInit(void)
{
    //
    // Enable Peripheral Clocks 
    //
    //SysCtlPeripheralEnable(SYSCTL_PERIPH_UART1); //UART
    //SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOB); //UART
    SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOF);

    //
    // Enable pin PF0 for GPIOInput
    //

    //
    //First open the lock and select the bits we want to modify in the GPIO commit register.
    //
    HWREG(GPIO_PORTF_BASE + GPIO_O_LOCK) = GPIO_LOCK_KEY;
    HWREG(GPIO_PORTF_BASE + GPIO_O_CR) = 0x1;

    //
    //Now modify the configuration of the pins that we unlocked.
    //
    GPIOPinTypeGPIOInput(GPIO_PORTF_BASE, GPIO_PIN_0);

    //
    // Enable pin PF4 for GPIOInput
    //
    GPIOPinTypeGPIOInput(GPIO_PORTF_BASE, GPIO_PIN_4);

				
			
		//Enable pull-up on PF4 and PF0
		GPIO_PORTF_PUR_R |=0x11;
}

void
uart_Init(void) {
	 // Enable pin PB1 for UART1 U1TX
    //
	  SysCtlPeripheralEnable(SYSCTL_PERIPH_UART1); //UART
    SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOB); //UART
    
		GPIOPinConfigure(GPIO_PB1_U1TX); //UART 
    GPIOPinTypeUART(GPIO_PORTB_BASE, GPIO_PIN_1); //UART
		
		UARTConfigSetExpClk(UART1_BASE, SysCtlClockGet(), 115200,
        (UART_CONFIG_WLEN_8 | UART_CONFIG_STOP_ONE | UART_CONFIG_PAR_NONE));
	
}


void
Interrupt_Init(void)
{
  IntEnable(INT_GPIOF);  							// enable interrupt 30 in NVIC (GPIOF)
	IntPrioritySet(INT_GPIOF, 0x00); 		// configure GPIOF interrupt priority as 0
	GPIO_PORTF_IM_R |= 0x11;   		// arm interrupt on PF0 and PF4
	GPIO_PORTF_IS_R &= ~0x11;     // PF0 and PF4 are edge-sensitive
  GPIO_PORTF_IBE_R &= ~0x11;   	// PF0 and PF4 not both edges trigger 
  GPIO_PORTF_IEV_R &= ~0x11;  	// PF0 and PF4 falling edge event
	
}

//interrupt handler
void GPIOPortF_Handler(void)
{
char str[3];
	//SW1 is pressed
	if(GPIO_PORTF_RIS_R&0x10)
	{
		// acknowledge flag for PF4
		GPIOIntClear(GPIO_PORTF_BASE, GPIO_PIN_4); 
		//counter imcremented by 1
		count=count+100;
		sprintf(str, "%d", count);//convert count to str array
		UARTCharPut(UART1_BASE, str[0]); 
		UARTCharPut(UART1_BASE, str[1]); 
		UARTCharPut(UART1_BASE, str[2]); 
		UARTCharPut(UART1_BASE, '\n'); 
		UARTCharPut(UART1_BASE, '\r'); 
	}
	
	//SW2 is pressed
  if(GPIO_PORTF_RIS_R&0x01)
	{
		// acknowledge flag for PF0
		GPIOIntClear(GPIO_PORTF_BASE, GPIO_PIN_0);
		//counter imcremented by 1
		count++;
		sprintf(str, "%d", count);  //convert count to str array
		UARTCharPut(UART1_BASE, str[0]); 
		UARTCharPut(UART1_BASE, str[1]); 
		UARTCharPut(UART1_BASE, str[2]); 
		UARTCharPut(UART1_BASE, '\n'); 
		UARTCharPut(UART1_BASE, '\r');
	}

}

int main (void)
{
		//initialize the GPIO ports	and UART1
		PortFunctionInit();
	
	//initialize UART1
		uart_Init();
		
		//configure the GPIOF interrupt
		Interrupt_Init();

		IntMasterEnable();       		// globally enable interrupt
	
	while(1){}//loop forever

}

